---
version: '3'

services:
  wordpress_phpunit:
    build: '.'
    environment:
      PHPUNIT_DB_HOST: 'mysql_phpunit'
    volumes:
      - '.:/app'
      - 'testsuite:/tmp'
  mysql_phpunit:
    image: 'mariadb:10.7'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'wordpress_test'
      MYSQL_ROOT_PASSWORD: ''

volumes:
  testsuite: { }
